[package]
name = "zkevm-basic"
version = "0.1.0"
edition = "2021"
description = "zkEVM basic example"
authors = ["Polygon Labs"]
readme = "README.md"

[dependencies]
pil2-components = { path = "../../../components" }
# starks-lib-c = { path = "../../lib/starks-lib-c" }
# stark = { path = "../../lib/provers/stark" }
# proofman-cli = { path = "../../cli" }
# pilout = { path = "../../pilout" }
# log = { version = "0.4", default-features = false }
# env_logger = { version = "0.11", default-features = false }
goldilocks = { path = "../../../goldilocks"}
# serde = { version = "1.0.130", features = ["derive"] }
# serde_json = "1.0.68"
# clap = { version = "4.5", features = ["derive", "env"] }