[package]
name = "proofman-old"
version = "0.1.0"
authors = ["Polygon Labs"]
edition = "2021"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
goldilocks = { path = "../../goldilocks"}
log = { workspace = true }
env_logger = { workspace = true }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
structopt = { version = "0.3", default-features = false }
pilout = { path = "../../pilout" }
crossbeam-channel = "0.5.8"
util = { path = "../../util" }
colored = "2"
starks-lib-c = { path = "../../lib/starks-lib-c" }

[dev-dependencies]
rand = "0.8"
criterion = "0.5.1"

[features]
default = ["no_lib_link"]
no_lib_link = []

[[bench]]
name = "trace_bench"
harness = false
