// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "33bfb3f4fdc39db28423bfdd46bc31f85049e0fd141f67a39cc96021f2194c4a";

pub const MERKLE_TREE_ARITY: u64 = 4;

//AIRGROUP CONSTANTS

pub const FIBONACCI_ML_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const FIBONACCI_ML_AIR_IDS: &[usize] = &[0];


//PUBLICS
use serde::Deserialize;
use serde::Serialize;
#[allow(unused_imports)]
use serde_arrays;



#[derive(Debug, Serialize, Deserialize)]
pub struct FibonacciPublics {
    #[serde(default)]
    pub in1: u64,
    #[serde(default)]
    pub in2: u64,
    #[serde(default)]
    pub out: u64,
    
}

impl Default for FibonacciPublics {
    fn default() -> Self {
        Self {  
            in1: 0,  
            in2: 0,  
            out: 0, 
        }
    }
}

values!(FibonacciPublicValues<F> {
 in1: F, in2: F, out: F,
});
  
trace_row!(FibonacciMLFixedRow<F> {
 L1: F,
});
pub type FibonacciMLFixed<F> = GenericTrace<FibonacciMLFixedRow<F>, 1024, 0, 0>;

trace_row!(FibonacciMLTraceRow<F> {
 a:F, b:F,
});

pub type FibonacciMLTrace<F> = GenericTrace<FibonacciMLTraceRow<F>, 1024, 0, 0>;

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
];

/// Display name for every `(airgroup_id, air_id)` pair, derived directly from the
/// PILOUT. Lets code resolve an AIR name without a loaded setup/`GlobalInfo`.
pub const AIR_NAMES: &[(usize, usize, &str)] = &[
    (0, 0, "FibonacciML"),
];