[package]
name = "prover-mocked"
version = "0.1.0"
authors = ["Polygon Labs"]
edition = "2021"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
proofman = { path = "../../../old/proofman-old" }
util = { path = "../../../util" }
log = { workspace = true }
