[package]
name = "fibv"
version = "0.1.0"
edition = "2021"
description = "Examples of how to use the proofman prover and verifier"
authors = ["Polygon Labs"]
readme = "README.md"

[dependencies]
proofman = { path = "../../../old/proofman-old" }
starks-lib-c = { path = "../../../lib/starks-lib-c" }
stark = { path = "../../../lib/provers/stark" }
proofman-cli = { path = "../../../cli" }
pilout = { path = "../../../pilout" }
log = { workspace = true }
env_logger = { workspace = true }
goldilocks = { path = "../../../goldilocks"}
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
clap = { version = "4.5", features = ["derive", "env"] }