[package]
name = "fibonacci-vadcop-old"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
common = { path = "../../common" }
goldilocks = { path = "../../goldilocks" }
wcmanager = { path = "../../wcmanager" }
log = { workspace = true }
env_logger = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"