// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "919523ecee72727007b4a88e8574634c84686025f6edc668957733d0afc3c425";

pub const MERKLE_TREE_ARITY: u64 = 4;

//AIRGROUP CONSTANTS

pub const HASHES_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const BLAKE_3_AIR_IDS: &[usize] = &[0];

  
trace_row!(Blake3FixedRow<F> {
 CLK_0: F, CONN: [F; 2], ID: F, RANGE1: F, RANGE2: F, A: F, B: F, OFFSET: F, ROTATION: F, C_ROT: [F; 2], __L1__: F,
});
pub type Blake3Fixed<F> = GenericTrace<Blake3FixedRow<F>, 1048576, 0, 0>;

trace_row!(Blake3TraceRow<F> {
 in_use:bit, va:[u8; 4], vb:[u8; 4], vc:[u8; 4], vd:[u8; 4], x:[u8; 4], y:[u8; 4], va_prime:[u8; 4], vd_prime:[u8; 4], vc_prime:[u8; 4], vb_prime_s:[[u8; 2]; 4], va_prime_prime:[u8; 4], vd_prime_prime:[u8; 4], vc_prime_prime:[u8; 4], vb_prime_prime_s:[[u8; 2]; 4], mul_range:u64, mul_table:u64,
});

pub type Blake3Trace<R> = GenericTrace<R, 1048576, 0, 0>;

values!(Blake3AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
    (0, 0, PackedInfoConst {
        is_packed: true,
        num_packed_words: 11,
        unpack_info: &[1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 64, 64],
    }),
];