// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use proofman_fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "bd30f4e1af98190a3ff66086774b0c545cdad1e702e8eb9cf57abbad816e8b3c";

//AIRGROUP CONSTANTS

pub const HASHES_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const BLAKE_2_B_AIR_IDS: &[usize] = &[0];

pub const SHA_2_AIR_IDS: &[usize] = &[1];

pub const BLAKE_3_AIR_IDS: &[usize] = &[2];

  
trace_row!(Blake2bFixedRow<F> {
 CLK_0: F, BLOCK_ID: F, A: F, B: F, C: F, __L1__: F,
});
pub type Blake2bFixed<F> = GenericTrace<Blake2bFixedRow<F>, 65536, 0, 0>;

trace_row!(Blake2bTraceRow<F> {
 va:[u16; 4], vb:[u8; 8], vc:[u16; 4], vd:[u8; 8], x:[u16; 4], y:[u16; 4], va_prime:[u8; 8], vd_prime:[u8; 8], vc_prime:[u8; 8], vb_prime:[u8; 8], va_prime_prime:[u8; 8], vd_prime_prime:[u8; 8], vc_prime_prime:[u8; 8], vb_pp_xor:[u8; 8], vb_pp_t:[bit; 2], mul_table:u64, mul_range:u64,
});

pub type Blake2bTrace<R> = GenericTrace<R, 65536, 0, 0>;

trace_row!(Sha2FixedRow<F> {
 CLK_0: F, SHA2_P3K: [F; 4], SHA2_P3O: [F; 4], SHA2_CHU: [F; 2], SHA2_CHR: [F; 2], SHA2_CHO: [F; 2], SHA2_RV0: [F; 2], SHA2_RV1: [F; 2], SHA2_RV2: [F; 2], SHA2_RV3: [F; 2], SHA2_CV: [F; 1], __L1__: F,
});
pub type Sha2Fixed<F> = GenericTrace<Sha2FixedRow<F>, 524288, 0, 1>;

trace_row!(Sha2TraceRow<F> {
 sa:[F; 32], se:[F; 32], sw:[F; 32], bs0:[F; 16], bs1:[F; 16], mj:[F; 16], ss0:[F; 16], ss1:[F; 16], chv:[F; 32], ca:[F; 4], ce:[F; 4], cw:[F; 4], sha2_mul_p3:[F; 4], sha2_mul_chr:[F; 2], sha2_mul_range:[F; 2], sha2_mul_carry:[F; 1],
});

pub type Sha2Trace<F> = GenericTrace<Sha2TraceRow<F>, 524288, 0, 1>;

trace_row!(Blake3FixedRow<F> {
 CLK_0: F, BLOCK_ID: F, A: F, B: F, ROTATION: F, C_ROT: [F; 2], __L1__: F,
});
pub type Blake3Fixed<F> = GenericTrace<Blake3FixedRow<F>, 524288, 0, 2>;

trace_row!(Blake3TraceRow<F> {
 va:[[u16; 2]; 4], vb:[[u8; 4]; 4], vc:[[u16; 2]; 4], vd:[[u8; 4]; 4], x:[[u16; 2]; 4], y:[[u16; 2]; 4], va_prime:[[u8; 4]; 4], vd_prime:[[u8; 4]; 4], vc_prime:[[u8; 4]; 4], vb_prime_s:[[[u8; 2]; 4]; 4], va_prime_prime:[[u8; 4]; 4], vd_prime_prime:[[u8; 4]; 4], vc_prime_prime:[[u8; 4]; 4], vb_pp_xor:[[u8; 4]; 4], vb_pp_t:[bit; 4], mul_table:u64, mul_range:u64,
});

pub type Blake3Trace<R> = GenericTrace<R, 524288, 0, 2>;

values!(Blake2bAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Sha2AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Blake3AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
    (0, 0, PackedInfoConst {
        is_packed: true,
        num_packed_words: 17,
        unpack_info: &[16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 64, 64],
    }),
    (0, 2, PackedInfoConst {
        is_packed: true,
        num_packed_words: 33,
        unpack_info: &[16, 16, 16, 16, 16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 64, 64],
    }),
];

/// Display name for every `(airgroup_id, air_id)` pair, derived directly from the
/// PILOUT. Lets code resolve an AIR name without a loaded setup/`GlobalInfo`.
pub const AIR_NAMES: &[(usize, usize, &str)] = &[
    (0, 0, "Blake2b"),
    (0, 1, "Sha2"),
    (0, 2, "Blake3"),
];