[package]
name = "fibonacci-vadcop"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
proofman-common = { path = "../../common" }
proofman = { path = "../../proofman" }
proofman-setup = { path = "../../setup" }

env_logger = { workspace = true }
log = { workspace = true }
p3-goldilocks = { workspace = true }
p3-field = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
