[package]
name = "stark"
version = "0.1.0"
authors = ["Polygon Labs"]
edition = "2021"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
proofman-util = { path = "../../util" }
starks-lib-c = { path = "../starks-lib-c" }
transcript = { path = "../../transcript" }
proofman-common = { path = "../../common" }
proofman-setup = { path = "../../setup" }
proofman-hints = { path = "../../hints" }

log = { workspace = true }
p3-goldilocks = { workspace = true }
p3-field = { workspace = true }

serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_derive = "1.0.196"

[features]
default = []