[package]
name = "transcript"
version = "0.7.0"
edition = "2021"

[dependencies]
proofman-starks-lib-c = { path = "../provers/starks-lib-c" }

[features]
default = []
no_lib_link = ["proofman-starks-lib-c/no_lib_link"]
gpu = ["proofman-starks-lib-c/gpu"]