[package]
name = "proofman-witness"
description = "Witness library, component, and manager traits for the PIL2 proofman framework"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
proofman-common = { path = "../common" }

proofman-fields.workspace = true
libloading.workspace = true


[features]
default = []
