[package]
name = "pilout"
version = "0.5.0"
edition = "2021"

[dependencies]
bytes.workspace = true
prost.workspace = true
log.workspace = true
serde = { version = "1", features = ["derive"] }  # Add serde

[build-dependencies]
prost-build.workspace = true
