[package]
name = "proofman"
version = "0.0.1"
authors = ["Polygon Labs"]
edition = "2021"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
goldilocks = { path = "../goldilocks"}
log = { version = "0.4.20" }
env_logger = "0.11"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
structopt = { version = "0.3", default-features = false }
pilout = { path = "../pilout" }
crossbeam-channel = "0.5.8"
criterion = "0.5.1"

[dev-dependencies]
rand = "0.8"
criterion = "0.5.1"

[[bench]]
name = "trace_bench"
opt-level = 3
harness = false
