[package]
name = "pil2-proofman-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
plonky2_field = { path = "../plonky2/field", default-features = false, features = [] }
plonky2_util = { path = "../plonky2/util" }
