[package]
name = "zkevm-example"
version = "0.0.1"
description = "Example of zkEVM"
authors = ["Polygon Labs"]
edition = "2021"
readme = "README.md"

[dependencies]
proofman = { path = "../../proofman" }
estark = { path = "../../estark" }
pilout = { path = "../../pilout" }
log = { version = "0.4", default-features = false }
env_logger = { version = "0.10", default-features = false }
structopt = { version = "0.3", default-features = false }
math = { package = "winter-math", version = "0.7.1", default-features = false }
crossbeam-channel = "0.5.8"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
num-bigint = "0.4.2"
rayon = "1.8.0"

