[package]
name = "estark"
version = "0.0.1"
authors = ["Polygon-zkEvm"]
edition = "2021"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"

[dev-dependencies]
