[package]
name = "pil2-stark-setup"
description = "Setup and proving/verifying-key generation for the pil2-stark prover"
rust-version = "1.89"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "proofman-setup"
path = "src/main.rs"

[features]
default = []

[dependencies]
proofman-starks-lib-c = { path = "../../provers/starks-lib-c" }
proofman-fields = { workspace = true, features = ["verify"] }
proofman-common = { workspace = true }
proofman-util = { workspace = true }
stark-recurser = { path = "../stark-recurser" }
pilout = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
indexmap = { version = "2", features = ["serde"] }
rug = "1"
tempfile = "3"
rayon = { workspace = true }
clap = { version = "4.5.38", features = ["derive", "env"] }
which = "6"

# Distributed mode (mpi) is only supported on Linux x86_64
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
mpi = { version = "0.8.0" }
