[package]
name = "pil2-components-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proofman = { path = "../proofman" }
goldilocks = { path = "../goldilocks" }
log = { version = "0.4.20" }