[package]
name = "proofman-util"
description = "Low-level utilities (device buffers, timers, helpers) for the PIL2 proofman framework"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
colored.workspace = true
sysinfo.workspace = true
serde.workspace = true
bincode.workspace = true