[package]
name = "proofman-util"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
colored.workspace = true
p3-field.workspace = true
tracing.workspace = true
sysinfo.workspace = true