[package]
name = "pil2-stark"
version = "0.1.0"
edition = "2021"

[dependencies]
pilout = { path = "../pilout" }
common = { path = "../common" }
wcmanager = { path = "../wcmanager" }
log = { workspace = true }
# tokio = { version = "1.0", features = ["full"] }
futures = "0.3"