// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use proofman_fields::PrimeField64;
use std::fmt;

pub const PILOUT_HASH: &str = "2b2f0f7504193c38e27e44264351eba7e1acce633b578077c49e50ebf6825752";

//AIRGROUP CONSTANTS

pub const CONNECTION_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const CONNECTION_AIR_IDS: &[usize] = &[0];

  
trace_row!(ConnectionFixedRow<F> {
 S1: F, S2: F, S3: F, ID: F, __L1__: F,
});
pub type ConnectionFixed<F> = GenericTrace<ConnectionFixedRow<F>, 1024, 0, 0>;

trace_row!(ConnectionTraceRow<F> {
 a:F, b:F, c:F,
});

pub type ConnectionTrace<F> = GenericTrace<ConnectionTraceRow<F>, 1024, 0, 0>;

/// Display name for every `(airgroup_id, air_id)` pair, derived directly from the
/// PILOUT. Lets code resolve an AIR name without a loaded setup/`GlobalInfo`.
pub const AIR_NAMES: &[(usize, usize, &str)] = &[
    (0, 0, "Connection"),
];