[package]
name = "fibfull"
version = "0.0.1"
description = "Examples of how to use the proofman prover and verifier"
authors = ["Polygon Labs"]
edition = "2021"
readme = "README.md"
build = "build.rs"

[dependencies]
proofman = { path = "../../proofman" }
estark = { path = "../../lib/provers/estark" }
pilout = { path = "../../pilout" }
log = { version = "0.4", default-features = false }
env_logger = { version = "0.11", default-features = false }
structopt = { version = "0.3", default-features = true }
math = { package = "winter-math", version = "0.8", default-features = false }
crossbeam-channel = "0.5.8"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
libc = "*"