[package]
name = "pil2-std-lib"
description = "PIL2 standard library: range checks, lookups, and sum/product arguments for proofman"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
proofman-common.workspace = true
proofman-hints.workspace = true
proofman-util.workspace = true
tracing.workspace = true
proofman-fields.workspace = true
rayon.workspace = true
proofman-witness.workspace = true
colored.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true

[features]
default = []
