//! Solidity verifier artifacts, the analogue of what the plonk/fflonk path
//! emits.
//!
//! That path produces two layers:
//!
//! 1. **The protocol verifier** -- `FflonkVerifier.sol` / `PlonkVerifier.sol`,
//!    generated by `snarkjs zkey export solidityverifier` from the zkey. It
//!    holds the pairing check and exposes
//!    `verifyProof(bytes32[24], uint256[1])`.
//! 2. **The wrapper** -- `{Name}Verifier.sol` and `I{Name}Verifier.sol`,
//!    generated from tera templates in `stark-recurser`. It hashes the public
//!    values, pins the vadcop-final root, decodes the proof and calls layer 1.
//!
//! This module implements layer 2. Layer 1 has no generator for SHPLONK:
//! snarkjs only knows fflonk's fixed three-opening-set structure, so the
//! pairing check has to be written rather than generated. See
//! [`PROOF_LAYOUT_NOTE`].
//!
//! One thing does not carry over. The plonk wrapper decodes a fixed
//! `[24]`-element proof, because fflonk and plonk have constant proof size.
//! SHPLONK does not: it emits one commitment per `f_i` plus `W` and `W'`, and
//! one evaluation per (polynomial, opening point). So the decode width is
//! derived from the setup here rather than hardcoded, and
//! [`ProofLayout`] is the single definition of that order shared by the
//! encoder and the generated contract.

use crate::proof::{INV_KEY, INV_ZH_KEY, UNEVALUATED_POL, W_KEY, WP_KEY, ShPlonkProof, commitment_key, evaluation_key};
use crate::setup::ShPlonkSetup;
use anyhow::{Context, Result, bail};

/// Why layer 1 is absent, recorded where someone will look for it.
pub const PROOF_LAYOUT_NOTE: &str = "\
SHPLONK has no snarkjs solidity-verifier generator: snarkjs implements fflonk's \
fixed three-opening-set structure, while pil-fflonk's opening set is data driven \
over the f_i declared in the setup. The pairing check must be authored.";

/// The canonical order of a proof's field elements.
///
/// Both the Rust encoder and the generated Solidity read this order, so it is
/// defined once. It is reconstructible from the verification key alone -- the
/// verifier never needs the proof to tell it the layout:
///
/// 1. Each `f_i` commitment, in index order, as `(x, y)`.
/// 2. `W`, then `W'`, as `(x, y)`.
/// 3. Each evaluation, walking `f_i` in index order, then that `f_i`'s opening
///    points in declared order, then its polynomials in declared order.
///    `Q` is skipped -- the verifier reconstructs it.
/// 4. `inv`, then `invZh`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProofLayout {
    /// Commitment keys in order; each contributes two words.
    pub commitments: Vec<String>,
    /// Evaluation keys in order; each contributes one word.
    pub evaluations: Vec<String>,
}

impl ProofLayout {
    pub fn from_setup(setup: &ShPlonkSetup) -> Self {
        let mut commitments: Vec<String> = setup.f.iter().map(|f| commitment_key(f.index)).collect();
        commitments.push(W_KEY.to_string());
        commitments.push(WP_KEY.to_string());

        let mut evaluations = Vec::new();
        for f in &setup.f {
            for &point in &f.opening_points {
                for pol in &f.pols {
                    if pol == UNEVALUATED_POL {
                        continue;
                    }
                    let key = evaluation_key(pol, point);
                    // A polynomial can appear in more than one f_i; its
                    // evaluation at a given point is one word regardless.
                    if !evaluations.contains(&key) {
                        evaluations.push(key);
                    }
                }
            }
        }
        evaluations.push(INV_KEY.to_string());
        evaluations.push(INV_ZH_KEY.to_string());

        Self { commitments, evaluations }
    }

    /// Total 32-byte words: two per commitment, one per evaluation.
    pub fn word_count(&self) -> usize {
        self.commitments.len() * 2 + self.evaluations.len()
    }
}

impl ShPlonkProof {
    /// Flatten the proof into `proofBytes` words, in [`ProofLayout`] order.
    ///
    /// Values stay decimal strings: converting them to 32-byte words needs
    /// field arithmetic this crate does not carry, so the caller does that
    /// step. The ordering -- the part that must agree with the contract -- is
    /// settled here.
    pub fn to_calldata_words(&self, layout: &ProofLayout) -> Result<Vec<String>> {
        let mut out = Vec::with_capacity(layout.word_count());

        for key in &layout.commitments {
            let point = self.polynomials.get(key).with_context(|| format!("proof is missing commitment {key:?}"))?;
            if point.len() != 3 {
                bail!("commitment {key:?} has {} coordinates, want 3", point.len());
            }
            if point[2] != "1" {
                bail!("commitment {key:?} is not affine (z = {:?})", point[2]);
            }
            out.push(point[0].clone());
            out.push(point[1].clone());
        }

        for key in &layout.evaluations {
            let value = self.evaluations.get(key).with_context(|| format!("proof is missing evaluation {key:?}"))?;
            out.push(value.clone());
        }

        Ok(out)
    }
}

/// The verifier wrapper contract, `{Name}Verifier.sol`.
///
/// Mirrors `stark-recurser`'s `verifier.sol.tera`, with the proof width taken
/// from `layout` instead of the fixed 24.
pub fn gen_solidity(
    name: &str,
    root_c: &[u64; 4],
    layout: &ProofLayout,
    has_program_vk: bool,
    first_is_vk: bool,
) -> String {
    let camel = capitalise(name);
    let words = layout.word_count();

    let vk_param = if has_program_vk { "        bytes32 programVK,\n" } else { "" };
    let vk_arg = if has_program_vk { "programVK, " } else { "" };
    let hash_operands = match (has_program_vk, first_is_vk) {
        (true, true) => "programVK, publicValues, rootCVadcopFinal",
        (true, false) => "publicValues, programVK, rootCVadcopFinal",
        (false, _) => "publicValues, rootCVadcopFinal",
    };

    format!(
        r#"// SPDX-License-Identifier: AGPL-3.0
pragma solidity ^0.8.20;

import {{I{camel}Verifier}} from "./I{camel}Verifier.sol";
import {{PilFflonkVerifier}} from "./PilFflonkVerifier.sol";

/// @title {camel} Verifier
/// @author SilentSig
/// @notice This contract implements a solidity verifier for {camel}.
contract {camel}Verifier is PilFflonkVerifier, I{camel}Verifier {{
    error InvalidProof();

    function VERSION() external pure returns (string memory) {{
        return "v1.2.0-alpha";
    }}

    /// @notice Root constant as bytes32 (pre-packed to match the original uint64[4] layout)
    function getRootCVadcopFinal() external pure returns (bytes32) {{
        return bytes32(
            abi.encodePacked(
                uint64({}),
                uint64({}),
                uint64({}),
                uint64({})));
    }}

    uint256 internal constant _RFIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @notice Number of 32-byte words in a proof: two per commitment
    /// ({} f_i plus W and Wp) and one per evaluation ({}).
    /// Unlike fflonk and plonk, SHPLONK's proof size depends on the setup, so
    /// this is generated rather than fixed.
    uint256 internal constant _PROOF_WORDS = {words};

    /// @notice Hashes the public values into a field element inside BN254.
    function hashPublicValues(
{vk_param}        bytes32 rootCVadcopFinal,
        bytes calldata publicValues
    ) public pure returns (uint256) {{
        return uint256(
            sha256(abi.encodePacked({hash_operands}))
        ) % _RFIELD;
    }}

    /// @notice Verifies a proof with given public values and vkey.
    function verifySnarkProof(
{vk_param}        bytes32 rootCVadcopFinal,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external view {{
        uint256 publicValuesDigest = hashPublicValues({vk_arg}rootCVadcopFinal, publicValues);

        uint256[{words}] memory proofDecoded = abi.decode(proofBytes, (uint256[{words}]));

        bool success = this.verifyProof(proofDecoded, [publicValuesDigest]);

        if (!success) {{
            revert InvalidProof();
        }}
    }}
}}
"#,
        root_c[0],
        root_c[1],
        root_c[2],
        root_c[3],
        layout.commitments.len() - 2,
        layout.evaluations.len(),
    )
}

/// The verifier interface, `I{Name}Verifier.sol`.
pub fn gen_iverifier(name: &str, has_program_vk: bool) -> String {
    let camel = capitalise(name);
    let vk_param = if has_program_vk { "        bytes32 programVK,\n" } else { "" };

    format!(
        r#"// SPDX-License-Identifier: AGPL-3.0
pragma solidity ^0.8.20;

/// @title I{camel} Verifier
/// @author SilentSig
/// @notice Interface of the solidity verifier for {camel}.
interface I{camel}Verifier {{
    function VERSION() external pure returns (string memory);

    function getRootCVadcopFinal() external pure returns (bytes32);

    function verifySnarkProof(
{vk_param}        bytes32 rootCVadcopFinal,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external view;
}}
"#
    )
}

fn capitalise(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::proof::commitment_key;
    use std::collections::BTreeMap;

    const VKEY: &str = include_str!("../tests/fixtures/pilfflonk.vkey");

    fn real_setup() -> ShPlonkSetup {
        ShPlonkSetup::from_vkey_json(&serde_json::from_str(VKEY).unwrap()).unwrap()
    }

    fn proof_for(setup: &ShPlonkSetup, layout: &ProofLayout) -> ShPlonkProof {
        let mut polynomials = BTreeMap::new();
        for key in &layout.commitments {
            polynomials.insert(key.clone(), vec!["11".to_string(), "22".to_string(), "1".to_string()]);
        }
        let mut evaluations = BTreeMap::new();
        for key in &layout.evaluations {
            evaluations.insert(key.clone(), "33".to_string());
        }
        let _ = setup;
        ShPlonkProof { polynomials, evaluations }
    }

    #[test]
    fn layout_covers_the_real_setup() {
        let setup = real_setup();
        let layout = ProofLayout::from_setup(&setup);

        // 9 f_i plus W and Wp.
        assert_eq!(layout.commitments.len(), 11);
        assert_eq!(layout.commitments[0], commitment_key(0));
        assert_eq!(layout.commitments[9], W_KEY);
        assert_eq!(layout.commitments[10], WP_KEY);

        // inv and invZh come last.
        let n = layout.evaluations.len();
        assert_eq!(layout.evaluations[n - 2], INV_KEY);
        assert_eq!(layout.evaluations[n - 1], INV_ZH_KEY);

        // Q is never evaluated.
        assert!(!layout.evaluations.iter().any(|k| k == UNEVALUATED_POL));

        assert_eq!(layout.word_count(), 11 * 2 + n);
    }

    #[test]
    fn layout_is_deterministic() {
        let setup = real_setup();
        assert_eq!(ProofLayout::from_setup(&setup), ProofLayout::from_setup(&setup));
    }

    #[test]
    fn layout_has_no_duplicate_keys() {
        let layout = ProofLayout::from_setup(&real_setup());

        let mut seen = layout.evaluations.clone();
        seen.sort();
        let before = seen.len();
        seen.dedup();
        assert_eq!(seen.len(), before, "duplicate evaluation key in the layout");

        let mut seen = layout.commitments.clone();
        seen.sort();
        let before = seen.len();
        seen.dedup();
        assert_eq!(seen.len(), before, "duplicate commitment key in the layout");
    }

    /// The encoder and the contract must agree on the word count, or calldata
    /// decoding silently misaligns.
    #[test]
    fn calldata_length_matches_the_generated_contract() {
        let setup = real_setup();
        let layout = ProofLayout::from_setup(&setup);
        let proof = proof_for(&setup, &layout);

        let words = proof.to_calldata_words(&layout).unwrap();
        assert_eq!(words.len(), layout.word_count());

        let sol = gen_solidity("fibonacci", &[1, 2, 3, 4], &layout, false, false);
        assert!(
            sol.contains(&format!("uint256[{}] memory proofDecoded", layout.word_count())),
            "contract decode width does not match the layout"
        );
        assert!(sol.contains(&format!("_PROOF_WORDS = {};", layout.word_count())));
    }

    #[test]
    fn calldata_follows_the_layout_order() {
        let setup = real_setup();
        let layout = ProofLayout::from_setup(&setup);

        let mut proof = proof_for(&setup, &layout);
        // Make f0's x distinguishable, and the first evaluation too.
        proof.polynomials.insert(commitment_key(0), vec!["101".into(), "102".into(), "1".into()]);
        proof.evaluations.insert(layout.evaluations[0].clone(), "999".into());

        let words = proof.to_calldata_words(&layout).unwrap();
        assert_eq!(words[0], "101", "f0.x must lead");
        assert_eq!(words[1], "102");
        assert_eq!(words[layout.commitments.len() * 2], "999", "evaluations follow all commitments");
    }

    #[test]
    fn rejects_a_non_affine_commitment() {
        let setup = real_setup();
        let layout = ProofLayout::from_setup(&setup);
        let mut proof = proof_for(&setup, &layout);
        proof.polynomials.insert(W_KEY.to_string(), vec!["1".into(), "2".into(), "3".into()]);

        let err = proof.to_calldata_words(&layout).unwrap_err().to_string();
        assert!(err.contains("not affine"), "unexpected error: {err}");
    }

    #[test]
    fn rejects_a_proof_missing_a_layout_entry() {
        let setup = real_setup();
        let layout = ProofLayout::from_setup(&setup);
        let mut proof = proof_for(&setup, &layout);
        proof.evaluations.remove(INV_ZH_KEY);

        assert!(proof.to_calldata_words(&layout).is_err());
    }

    #[test]
    fn wrapper_pins_the_root_and_names_the_contract() {
        let layout = ProofLayout::from_setup(&real_setup());
        let sol = gen_solidity("fibonacci", &[10, 20, 30, 40], &layout, false, false);

        assert!(sol.contains("contract FibonacciVerifier is PilFflonkVerifier, IFibonacciVerifier"));
        for v in [10u64, 20, 30, 40] {
            assert!(sol.contains(&format!("uint64({v})")), "root_c component {v} not pinned");
        }
        assert!(sol.contains("% _RFIELD"));
    }

    #[test]
    fn wrapper_threads_the_program_vk_when_present() {
        let layout = ProofLayout::from_setup(&real_setup());

        let without = gen_solidity("f", &[0; 4], &layout, false, false);
        assert!(!without.contains("programVK"));
        assert!(without.contains("abi.encodePacked(publicValues, rootCVadcopFinal)"));

        let vk_first = gen_solidity("f", &[0; 4], &layout, true, true);
        assert!(vk_first.contains("abi.encodePacked(programVK, publicValues, rootCVadcopFinal)"));

        let vk_last = gen_solidity("f", &[0; 4], &layout, true, false);
        assert!(vk_last.contains("abi.encodePacked(publicValues, programVK, rootCVadcopFinal)"));
    }

    #[test]
    fn interface_matches_the_wrapper_signature() {
        let iface = gen_iverifier("fibonacci", false);
        assert!(iface.contains("interface IFibonacciVerifier"));
        assert!(iface.contains("function verifySnarkProof("));
        assert!(iface.contains("function getRootCVadcopFinal() external pure returns (bytes32);"));
        assert!(!iface.contains("programVK"));

        let iface_vk = gen_iverifier("fibonacci", true);
        assert!(iface_vk.contains("bytes32 programVK,"));
    }
}
