[package]
name = "proofman-hints"
description = "Hint definitions and evaluation for the PIL2 proofman framework"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
proofman-starks-lib-c = { path = "../provers/starks-lib-c" }
proofman-common = { path = "../common" }
proofman-util = { path = "../util" }
proofman-fields = { path = "../fields" }
itoa.workspace = true

tracing.workspace = true

[features]
default = []