[package]
name = "proofman-common"
description = "Shared proof/setup contexts, traces, and STARK metadata types for the PIL2 proofman framework"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
build = "build.rs"

[dependencies]
proofman-starks-lib-c = { path = "../provers/starks-lib-c" }
proofman-util = { path = "../util" }

libloading.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
proofman-fields.workspace = true
proofman-macros.workspace = true
rayon.workspace = true
sysinfo.workspace = true
crossbeam-channel.workspace = true
borsh.workspace = true
thiserror.workspace = true
csv.workspace = true
num_cpus = "1.17.0"
env = "1.0.1"
colored.workspace = true
tracing-subscriber.workspace = true
crossbeam-queue = "0.3.12"
yansi = "1.0.1"
mpi = { version = "0.8.0", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[features]
default = ["mpi"]
mpi = ["dep:mpi"]
diagnostic = ["proofman-macros/diagnostic"]
cpu-only = ["proofman-starks-lib-c/cpu-only"]