// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
pub use proofman_macros::trace;
pub use proofman_macros::values;

use std::fmt;

use rayon::prelude::*;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "87f3653a4db13884fbbe818238a4285aec04349d50200b89d879576900b78ef0";

//AIRGROUP CONSTANTS

pub const ONE_INSTANCE_PROD_AIRGROUP_ID: usize = 0;

pub const ONE_INSTANCE_SUM_AIRGROUP_ID: usize = 1;

//AIR CONSTANTS

pub const AIR_PROD_AIR_IDS: &[usize] = &[0];

pub const AIR_SUM_AIR_IDS: &[usize] = &[0];

  
trace!(AirProdFixed<F> {
 __L1__: F,
},  0, 0, 256 );

trace!(AirProdTrace<F> {
 a: F, b: F, c: F,
},  0, 0, 256 );

trace!(AirSumFixed<F> {
 __L1__: F,
},  1, 0, 256 );

trace!(AirSumTrace<F> {
 a: F, b: F, c: F,
},  1, 0, 256 );
