// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
pub use proofman_macros::trace;
pub use proofman_macros::values;

use std::fmt;

use rayon::prelude::*;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "59791b815207dec00694edb9a8e42a211e0c434a45c3123b3fae4dd7ef3e4ed0";

//AIRGROUP CONSTANTS

pub const ONE_INSTANCE_PROD_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const AIR_PROD_AIR_IDS: &[usize] = &[0];

  
trace!(AirProdFixed<F> {
 __L1__: F,
},  0, 0, 256 );

trace!(AirProdTrace<F> {
 a: F, b: F, c: F,
},  0, 0, 256 );
