[package]
name = "proofman-macros"
version = "0.7.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
rayon = "1.10"

[features]
default = []
diagnostic = []
