// The verifier on what the setup writes (M16) for the Fibonacci fixture, regenerated by
// test/setup-fixtures.sh into PILFFLONK_JS_FIXTURES, with the ptau of τ = 1:
// - the digest the JS computes over pilfflonk.vkey.json is the one Rust sealed it with, and any
//   change to the vkey changes it;
// - the vkey's qVerifier, run on the evaluations of the Rust oracle (M14) at a point ξ
//   (setup/pilfflonk/tests/js_fixtures.rs), gives the oracle's Q(ξ): the conventions of the im
//   pols, the challenges and the fold agree;
// - a forged proof (proofs.js) verifies against the real vkey, and each change M19 lists is
//   rejected, through verify() and through bin/verify.js.
// Skipped, saying why, unless PILFFLONK_JS_FIXTURES names the directory.

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { before, test } from "node:test";

import { computeQ, verify } from "../src/verify.js";
import { fromObjectVk, vkeyDigest } from "../src/vkey.js";
import { errorsOf, forgeProof, randomness, recordingLogger } from "./proofs.js";
import { newCurve } from "./support.js";

const DIR = process.env.PILFFLONK_JS_FIXTURES || "";
const NO_FIXTURES =
    "PILFFLONK_JS_FIXTURES is not set: run test/setup-fixtures.sh to set up the Fibonacci and run these " +
    "tests on its provingKey/";
const VERIFY_BIN = join(dirname(fileURLToPath(import.meta.url)), "..", "bin", "verify.js");

// pil-fflonk/runtime/public.json: the Fibonacci's publics for the inputs 1 and 2 (M13).
const PUBLICS = ["1", "2", "590308608561184158373097535019708483037277117989374906445627411437315467687"];

if (!DIR) {
    test("the Fibonacci's provingKey/ (M16) and the oracle's Q(ξ) (M14)", { skip: NO_FIXTURES }, () => {});
} else {
    run(DIR);
}

function run(dir) {
    const vkeyPath = join(dir, "build", "provingKey", "fibonacci", "pilfflonk", "pilfflonk.vkey.json");
    const vkeyText = readFileSync(vkeyPath, "utf8");
    const vkey = () => JSON.parse(vkeyText);
    const fixture = JSON.parse(readFileSync(join(dir, "q_at_xi.json"), "utf8"));
    let curve;
    before(async () => {
        curve = await newCurve();
    });

    test("the JS digest of the vkey is the one the setup sealed it with", () => {
        const v = vkey();
        assert.match(v.digest, /^0x[0-9a-f]{64}$/);
        assert.equal(vkeyDigest(v), v.digest);
    });

    test("any change to the vkey changes its digest", () => {
        const base = vkey();
        const changes = [];
        const change = (name, f) => changes.push([name, f]);
        for (const key of Object.keys(base).filter((k) => k !== "digest")) {
            change(`drop ${key}`, (v) => delete v[key]);
        }
        change("nPublic", (v) => (v.nPublic += 1));
        change("power", (v) => (v.power -= 1));
        change("powerW", (v) => (v.powerW = 2));
        change("X_2", (v) => (v.X_2[1][1] = "1"));
        change("numChallenges", (v) => (v.numChallenges = [1]));
        change("evMap order", (v) => v.evMap.reverse());
        change("evMap prime", (v) => (v.evMap[5].prime = 2));
        change("layout name", (v) => (v.layout[2].pols[0].name = "l3"));
        change("layout offsets", (v) => (v.layout[4].offsets = [0, 1]));
        change("layout degree", (v) => (v.layout[5].degree += 1));
        change("boundaries", (v) => v.boundaries.push({ name: "firstRow" }));
        change("f0", (v) => (v.f0 = ["0", "0"]));
        change("f1", (v) => (v.f1 = ["1", "2"]));
        change("qDeg", (v) => (v.qDeg = 2));
        change("maxQDegree", (v) => (v.maxQDegree = 1));
        change("qVerifier op", (v) => (v.qVerifier.code[0].op = "add"));
        change("qVerifier number", (v) => (v.qVerifier.code[1].src[0].value = "2"));
        change("qVerifier tmpUsed", (v) => (v.qVerifier.tmpUsed += 1));
        change("a field more", (v) => (v.f2 = ["1", "2"]));
        const seen = new Map([[base.digest, "none"]]);
        for (const [name, f] of changes) {
            const v = vkey();
            f(v);
            const digest = vkeyDigest(v);
            assert.ok(!seen.has(digest), `${name} gives the digest of ${seen.get(digest)}`);
            seen.set(digest, name);
        }
        // But not the file's layout nor the order of its fields.
        const reordered = Object.fromEntries(Object.entries(base).reverse());
        assert.equal(vkeyDigest(JSON.parse(JSON.stringify(reordered))), base.digest);
    });

    test("the vkey is the Fibonacci's (plan M16)", () => {
        const vk = fromObjectVk(curve, vkey());
        assert.equal(vk.power, fixture.nBits);
        assert.equal(vk.nStages, 1);
        assert.equal(vk.qDeg, 1);
        assert.deepEqual(
            vk.layout.map((f) => [f.stage, f.pols.map((p) => p.name).join(), f.k, f.offsets.join()]),
            [
                [0, "Fibonacci.L1", 1, "0"],
                [0, "Fibonacci.LLAST", 1, "0"],
                [1, "l1", 1, "0,1"],
                [1, "l2", 1, "0,1"],
                [1, "Fibonacci.ImPol[0]", 1, "0"],
                [2, "Q0", 1, "0"],
            ],
        );
        assert.deepEqual(
            vk.evMap.map((e) => e.name),
            ["Fibonacci.L1", "Fibonacci.LLAST", "l1", "l2", "Fibonacci.ImPol[0]", "l1w", "l2w"],
        );
        assert.deepEqual(vk.commitmentNames, ["f2", "f3", "f4", "f5"]);
        // τ = 1: [L1] = L1(1)·G = G, and LLAST(1) = 0 commits to the point at infinity.
        assert.ok(curve.G1.eq(vk.fixedCommitments[0], curve.G1.g));
        assert.ok(curve.G1.isZero(vk.fixedCommitments[1]));
        assert.ok(curve.G2.eq(vk.X2.tau, curve.G2.g));
    });

    test("the challenges of the qVerifier are the AIR's challengesMap", () => {
        const vk = fromObjectVk(curve, vkey());
        assert.deepEqual(
            vk.challenges,
            fixture.challengesMap.map(({ stage, stageId }) => ({ stage, stageId })),
        );
        assert.deepEqual(
            fixture.challengesMap.map((c) => c.name),
            ["std_vc", "std_xi"],
        );
    });

    for (const c of fixture.cases) {
        test(`the qVerifier gives the oracle's Q(ξ): ${c.name}`, () => {
            const Fr = curve.Fr;
            const vk = fromObjectVk(curve, vkey());
            const e = (v) => Fr.e(BigInt(v));
            assert.deepEqual(Object.keys(c.evaluations).sort(), vk.evMap.map((m) => m.name).sort());
            const proof = { evaluations: vk.evMap.map((m) => e(c.evaluations[m.name])) };
            // std_vc is the challenge of stage nStages + 1; xiSeed = ξ, powerW being 1.
            assert.equal(vk.powerW, 1);
            const challenges = { stages: [], stdVc: e(c.challenges.std_vc), xiSeed: e(c.xi) };
            const { q } = computeQ(curve, vk, c.publics.map(e), proof, challenges, e(c.xi));
            assert.equal(Fr.toString(q), c.q);

            // Another value of any evaluation, public or of std_vc is another Q(ξ).
            const other = structuredClone(proof);
            other.evaluations[4] = Fr.add(other.evaluations[4], Fr.one);
            assert.notEqual(Fr.toString(computeQ(curve, vk, c.publics.map(e), other, challenges, e(c.xi)).q), c.q);
            const vc = { ...challenges, stdVc: Fr.add(challenges.stdVc, Fr.one) };
            assert.notEqual(Fr.toString(computeQ(curve, vk, c.publics.map(e), proof, vc, e(c.xi)).q), c.q);
        });
    }

    test("a forged proof verifies against the vkey, and every change M19 lists is rejected", async () => {
        const rand = randomness(curve, "setup.test");
        const plusOne = (v) => ((BigInt(v) + 1n) % curve.r).toString();
        const proof = forgeProof(curve, vkey(), PUBLICS);
        const check = async (v, publics, p) => {
            const logger = recordingLogger();
            return { result: await verify(v, publics, p, logger), errors: errorsOf(logger) };
        };
        assert.deepEqual(await check(vkey(), PUBLICS, proof), { result: true, errors: [] });

        for (const name of Object.keys(proof.polynomials)) {
            const p = structuredClone(proof);
            const other = curve.G1.toObject(rand.g1()).map(String);
            p.polynomials[name] = [other[0], other[1], "1"];
            assert.equal((await check(vkey(), PUBLICS, p)).result, false, name);
        }
        for (const name of Object.keys(proof.evaluations)) {
            const p = structuredClone(proof);
            p.evaluations[name] = plusOne(p.evaluations[name]);
            assert.equal((await check(vkey(), PUBLICS, p)).result, false, name);
        }
        for (let i = 0; i < PUBLICS.length; i++) {
            const publics = [...PUBLICS];
            publics[i] = plusOne(publics[i]);
            assert.equal((await check(vkey(), publics, proof)).result, false, `publics[${i}]`);
        }
        const v = vkey();
        v.layout[5].degree += 1;
        assert.deepEqual(await check(v, PUBLICS, proof), {
            result: false,
            errors: ["The digest of the vkey is not the digest of its contents (A.6)"],
        });
    });

    test("bin/verify.js: 0 for the forged proof, 1 for a tampered one", () => {
        const proof = forgeProof(curve, vkey(), PUBLICS);
        const tmp = mkdtempSync(join(tmpdir(), "pilfflonk-verify-"));
        try {
            const proofPath = join(tmp, "proof.json");
            const publicsPath = join(tmp, "publics.json");
            writeFileSync(proofPath, JSON.stringify(proof, null, 1));
            writeFileSync(publicsPath, JSON.stringify(PUBLICS));
            const runBin = () =>
                spawnSync(process.execPath, [VERIFY_BIN, vkeyPath, publicsPath, proofPath], { encoding: "utf8" });
            let out = runBin();
            assert.equal(out.status, 0, out.stderr);
            proof.evaluations.l1w = ((BigInt(proof.evaluations.l1w) + 1n) % curve.r).toString();
            writeFileSync(proofPath, JSON.stringify(proof, null, 1));
            out = runBin();
            assert.equal(out.status, 1, out.stderr);
        } finally {
            rmSync(tmp, { recursive: true, force: true });
        }
    });
}
