[package]
name = "proofman-starks-lib-c"
version = "0.7.1"
edition = "2021"

build = "build.rs"

[dependencies]
log.workspace = true
crossbeam-channel = "0.5.15"

[features]
default = []
no_lib_link = []
gpu = []
