// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use proofman_fields::PrimeField64;
use std::fmt;

pub const PILOUT_HASH: &str = "0ff920a7e8540d1baf86e397ce1531b6c029ab56b4a41ba69bc2291ae8a1bcc5";

//AIRGROUP CONSTANTS

pub const FIBONACCI_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const FIBONACCI_AIR_IDS: &[usize] = &[0];


//PUBLICS
use serde::Deserialize;
use serde::Serialize;
use serde_arrays;
use proofman_fields::Bn128;



#[derive(Debug, Serialize, Deserialize)]
pub struct FibonacciPublics {
    #[serde(default)]
    pub in1: Bn128,
    #[serde(default)]
    pub in2: Bn128,
    #[serde(default)]
    pub out: Bn128,
    
}

impl Default for FibonacciPublics {
    fn default() -> Self {
        Self {  
            in1: Bn128::default(),  
            in2: Bn128::default(),  
            out: Bn128::default(), 
        }
    }
}

values!(FibonacciPublicValues<F> {
 in1: F, in2: F, out: F,
});
  
trace_row!(FibonacciFixedRow<F> {
 L1: F, LLAST: F,
});
pub type FibonacciFixed<F> = GenericTrace<FibonacciFixedRow<F>, 256, 0, 0>;

trace_row!(FibonacciTraceRow<F> {
 l1:F, l2:F,
});

pub type FibonacciTrace<F> = GenericTrace<FibonacciTraceRow<F>, 256, 0, 0>;

/// Display name for every `(airgroup_id, air_id)` pair, derived directly from the
/// PILOUT. Lets code resolve an AIR name without a loaded setup/`GlobalInfo`.
pub const AIR_NAMES: &[(usize, usize, &str)] = &[
    (0, 0, "Fibonacci"),
];