[package]
name = "fibonacci-square"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
proofman-common = { path = "../../common" }
proofman-macros.workspace = true
proofman = { path = "../../proofman" }

# pil-std-lib = { git = "https://github.com/0xPolygonHermez/pil2-components.git", branch ="std_rust" }
#Local development
pil-std-lib = { path = "../../../pil2-components/lib/std/rs" }

env_logger.workspace = true
log.workspace = true
p3-goldilocks.workspace = true
p3-field.workspace = true

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
