[package]
name = "fibonacci-square"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["dylib"]

[dependencies]
proofman-common.workspace = true
proofman-macros.workspace = true
proofman-cli.workspace = true
proofman.workspace = true
pil-std-lib = {path = "../../pil2-components/lib/std/rs" }

env_logger.workspace = true
log.workspace = true
p3-goldilocks.workspace = true
p3-field.workspace = true

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
num-bigint = "0.4"

[build-dependencies]
proofman-cli.workspace = true
