[package]
name = "proofman-verifier"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
fields.workspace = true
serde = { version = "1.0.130", default-features = false, features = [
  "alloc",
  "derive",
] }
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
bincode = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }

[features]
default = ["std", "verify"]
std = ["dep:tracing", "dep:bincode", "serde/std"]
verify = ["fields/verify"]
parallel = ["std", "dep:rayon"]
