[package]
name = "common"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
publish = false

[dependencies]
pil2-stark-setup = { workspace = true }
proofman.workspace = true
proofman-common.workspace = true
proofman-fields.workspace = true
