// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
use proofman_common as common;
pub use proofman_macros::trace;

trace!(FibonacciSquareTrace<F> {
 a: F, b: F,
}, 1024);

trace!(ModuleTrace<F> {
 x: F, q: F, x_mod: F,
}, 1024);

trace!(U8AirTrace<F> {
 mul: F,
}, 256);

trace!(FibonacciSquareRomTrace<F> {
 line: F, flags: F,
}, 1024);
