[package]
name = "pilfflonk-setup"
description = "Setup for the pilfflonk backend (PIL2 over BN254 with fflonk): validation, grouping, bytecode and keys"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
pil-info = { workspace = true }
proofman-pilfflonk = { workspace = true }

[dev-dependencies]
num-bigint = { workspace = true }
pil2-pilout = { workspace = true }
serde_json = { workspace = true }
