// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use proofman_fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "a4957282bb064cbc0be84f275d7d38948f630e65eb34e70128185f3f97af0ddd";

//AIRGROUP CONSTANTS

pub const SIMPLE_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const SIMPLE_LEFT_AIR_IDS: &[usize] = &[0];

pub const SIMPLE_RIGHT_AIR_IDS: &[usize] = &[1];

pub const VIRTUAL_TABLE_SIMPLE_0_AIR_IDS: &[usize] = &[2];

  
trace_row!(SimpleLeftFixedRow<F> {
 __L1__: F,
});
pub type SimpleLeftFixed<F> = GenericTrace<SimpleLeftFixedRow<F>, 8, 0, 0>;

trace_row!(SimpleLeftTraceRow<F> {
 a:F, b:F, c:F, d:F, e:F, f:F, g:F, h:F, mul:F, k:[F; 7],
});

pub type SimpleLeftTrace<F> = GenericTrace<SimpleLeftTraceRow<F>, 8, 0, 0>;

trace_row!(SimpleRightFixedRow<F> {
 __L1__: F,
});
pub type SimpleRightFixed<F> = GenericTrace<SimpleRightFixedRow<F>, 8, 0, 1>;

trace_row!(SimpleRightTraceRow<F> {
 a:F, b:F, c:F, d:F, mul:F,
});

pub type SimpleRightTrace<F> = GenericTrace<SimpleRightTraceRow<F>, 8, 0, 1>;

trace_row!(VirtualTableSimple0FixedRow<F> {
 __ROW_INDEX__: F, COL_4_4_0: F, UID_4: F, __L1__: F,
});
pub type VirtualTableSimple0Fixed<F> = GenericTrace<VirtualTableSimple0FixedRow<F>, 16384, 0, 2>;

trace_row!(VirtualTableSimple0TraceRow<F> {
 multiplicity:[F; 5],
});

pub type VirtualTableSimple0Trace<F> = GenericTrace<VirtualTableSimple0TraceRow<F>, 16384, 0, 2>;

values!(SimpleLeftAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(SimpleRightAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(VirtualTableSimple0AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
];

/// Display name for every `(airgroup_id, air_id)` pair, derived directly from the
/// PILOUT. Lets code resolve an AIR name without a loaded setup/`GlobalInfo`.
pub const AIR_NAMES: &[(usize, usize, &str)] = &[
    (0, 0, "SimpleLeft"),
    (0, 1, "SimpleRight"),
    (0, 2, "VirtualTableSimple0"),
];