// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use proofman_fields::PrimeField64;
use std::fmt;

pub const PILOUT_HASH: &str = "53f427b85fbbaff14bb7986969279fe49224a6e20b0f2ca686039f3f8c22649f";

//AIRGROUP CONSTANTS

pub const ALL_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const ALL_AIR_IDS: &[usize] = &[0];


//PUBLICS
use serde::Deserialize;
use serde::Serialize;
use serde_arrays;
use proofman_fields::Bn128;



#[derive(Debug, Serialize, Deserialize)]
pub struct AllPublics {
    #[serde(default)]
    pub in1: Bn128,
    #[serde(default)]
    pub in2: Bn128,
    #[serde(default)]
    pub out: Bn128,
    
}

impl Default for AllPublics {
    fn default() -> Self {
        Self {  
            in1: Bn128::default(),  
            in2: Bn128::default(),  
            out: Bn128::default(), 
        }
    }
}

values!(AllPublicValues<F> {
 in1: F, in2: F, out: F,
});
  
trace_row!(AllFixedRow<F> {
 L1: F, LLAST: F, S1: F, S2: F, S3: F, ID: F, SEL: F, A: F, B: F, __L1__: F,
});
pub type AllFixed<F> = GenericTrace<AllFixedRow<F>, 256, 0, 0>;

trace_row!(AllTraceRow<F> {
 l1:F, l2:F, connection_a:F, connection_b:F, connection_c:F, permutation_a:F, permutation_b:F, permutation_c:F, permutation_d:F, permutation_selC:F, permutation_selD:F, plookup_sel:F, plookup_a:F, plookup_b:F, plookup_cc:F, plookup_mul:F,
});

pub type AllTrace<F> = GenericTrace<AllTraceRow<F>, 256, 0, 0>;

/// Display name for every `(airgroup_id, air_id)` pair, derived directly from the
/// PILOUT. Lets code resolve an AIR name without a loaded setup/`GlobalInfo`.
pub const AIR_NAMES: &[(usize, usize, &str)] = &[
    (0, 0, "All"),
];