[package]
name = "pil2-stark-recurser"
description = "STARK recursion setup tooling for the pil2-stark prover"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
categories = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
proofman-fields = { workspace = true, features = ["verify"] }
proofman-common = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
anyhow = { workspace = true }
tracing = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
tera = "1"

[dev-dependencies]
rand = { workspace = true }
serde_json = { workspace = true }
