name: CI Checks
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Set up Rust Toolchain
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: cargo test
        run: cargo test --workspace --features no_lib_link
  cargo-check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Set up Rust Toolchain
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Modify stark-prover-lib
        run: |
          sed -i 's/default = \["no_lib_link"\]/default = \[\]/g' ./provers/starks-lib-c/Cargo.toml
      - name: cargo check
        run: cargo check --workspace --features no_lib_link
  cargo-fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust Toolchain
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: cargo fmt
        run: cargo fmt -- --check
  cargo-fix:
    name: cargo fix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Set up Rust Toolchain
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Modify stark-prover-lib
        run: sed -i 's/default = \[\]/default = \["no_lib_link"\]/g' ./provers/starks-lib-c/Cargo.toml
      - name: cargo fix --workspace
        run: |
          # Run cargo fix on the project
          cargo fix --workspace --features no_lib_link --allow-dirty --allow-staged

          # Check for local git changes
          if ! git diff --exit-code; then
              echo "There are local changes after running 'cargo fix --workspace' ❌"
              exit 1
          else
              echo "No changes detected after running 'cargo fix --workspace' ✅"
          fi
  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Set up Rust Toolchain
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Modify stark-prover-lib
        run: sed -i 's/default = \[\]/default = \["no_lib_link"\]/g' ./provers/starks-lib-c/Cargo.toml
      - name: cargo clippy
        run: cargo clippy --workspace --features no_lib_link -- -D warnings
  cargo-audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust Toolchain
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: install cargo-audit
        run: cargo install cargo-audit
      - name: cargo audit
        run: cargo audit
  fibonacci-square:
    name: Test fibonacci square
    runs-on: [self-hosted, zisk]
    env:
      STARKS_LIB_C: ${{ github.workspace }}/pil2-stark/lib/libstarks.a
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install npm
        run: npm install -g npm
      - name: Check npm version
        run: npm --version

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install z3-solver
        run: | 
          python -m pip install z3-solver

      - name: Check out pil2-proofman-js
        uses: actions/checkout@v4
        with:
          repository: 0xPolygonHermez/pil2-proofman-js
          token: ${{ secrets.ZISK_CI_TOKEN }}
          ref: feature/setup
          path: pil2-proofman-js

      - name: Install pil2-proofman-js dependencies
        working-directory: pil2-proofman-js
        run: npm install

      - name: Check out pil2-compiler
        uses: actions/checkout@v4
        with:
          repository: 0xPolygonHermez/pil2-compiler
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: develop
          path: pil2-compiler

      - name: Install pil2-compiler dependencies
        working-directory: pil2-compiler
        run: npm install

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y protobuf-compiler build-essential libbenchmark-dev libomp-dev libgmp-dev nlohmann-json3-dev postgresql libpqxx-dev libpqxx-doc nasm libsecp256k1-dev libprotoc-dev libsodium-dev libprotobuf-dev libssl-dev cmake libgrpc++-dev uuid-dev

      - name: Check out pil2-stark
        uses: actions/checkout@v4
        with:
          repository: 0xPolygonHermez/pil2-stark
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: develop
          path: pil2-stark

      - name: Install pil2-stark
        working-directory: pil2-stark
        run: |
          git submodule init
          git submodule update
          make clean
          make starks_lib -j
          make -j bctree

      - name: Compile PIL
        run: |
          node pil2-compiler/src/pil.js ./examples/fibonacci-square/pil/build.pil -I ./pil2-components/lib/std/pil -o ./examples/fibonacci-square/pil/build.pilout

      - name: Generate setup
        run: |
          node pil2-proofman-js/src/main_setup.js -a ./examples/fibonacci-square/pil/build.pilout -b ./examples/fibonacci-square/build -t pil2-stark/build/bctree

      - name: Generate PIL Helpers
        run: |
          cargo run --bin proofman-cli pil-helpers --pilout ./examples/fibonacci-square/pil/build.pilout --path ./examples/fibonacci-square/src -o

      - name: Modify Cargo.toml
        run: |
          sed -i 's/# *"examples\/fibonacci-square"/"examples\/fibonacci-square"/' ./Cargo.toml

      - name: Modify stark-prover-lib
        run: |
          sed -i 's/default = \["no_lib_link"\]/default = \[\]/g' ./provers/starks-lib-c/Cargo.toml

      - name: Cargo build
        run: RUST_BACKTRACE=1 cargo build -v

      - name: Verify constraints
        run: |
          cargo run --bin proofman-cli verify-constraints --witness-lib ./target/debug/libfibonacci_square.so --proving-key examples/fibonacci-square/build/provingKey/ --public-inputs examples/fibonacci-square/src/inputs.json

      - name: Generate proof
        run: |
          cargo run --bin proofman-cli prove --witness-lib ./target/debug/libfibonacci_square.so --proving-key examples/fibonacci-square/build/provingKey/ --public-inputs examples/fibonacci-square/src/inputs.json --output-dir examples/fibonacci-square/build/proofs

      - name: Verify proof
        run: |
          node pil2-proofman-js/src/main_verify -k examples/fibonacci-square/build -p examples/fibonacci-square/build/proofs
