[package]
name = "fib4"
version = "0.1.0"
description = "Examples of how to use the proofman prover and verifier"
authors = ["Polygon Labs"]
edition = "2021"
readme = "README.md"

[dependencies]
proofman = { path = "../../proofman-old" }
starks-lib-c = { path = "../../lib/starks-lib-c" }
proofman-cli = { path = "../../cli" }
prover-mocked = { path = "../../lib/provers/mocked" }
log = { version = "0.4", default-features = false }
env_logger = { version = "0.11", default-features = false }
goldilocks = { path = "../../goldilocks"}
clap = { version = "4.5", features = ["derive", "env"] }
